force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <description>Payment</description>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Payment No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <description>Statement</description>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Agreement__c/Rental_Agreement__c.object-meta.xml
<CustomObject>
    <description>Rental Agreement</description>
    <label>Rental Agreement</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Rental Agreement No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Agreement__c/fields/Total_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoiced__c</fullName>
    <description>This will perform the apex rollup of Statement amounts from Statement</description>
    <label>Total Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental_Agreement__c/fields/Total_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments__c</fullName>
    <description>This will perform the apex rollup of Payments from Statement</description>
    <label>Total Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <description>Statement</description>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>Statement No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Statement__c/fields/Rental_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Rental_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Rental Agreement lookup detail</description>
    <label>Rental Agreement</label>
    <referenceTo>Rental_Agreement__c</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Statement__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>Total Amount</description>
    <formula>Amounts__c -  Additional_Fees__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RollUp_Methods.cls
public class RollUp_Methods 
{
public static void rollupStatementsToRentalAgreement(List<Statement__c> newList)
{
set<id> rentalAgreementSet = new set<id>();
for(Statement__c S:newList)
{
rentalAgreementSet.add(S.Rental_Agreement__c);    
} 
//This list will store the rental Agreement records which needs to be updates    
List<Rental_Agreement__c> rentalUpdates = new List<Rental_Agreement__c>();
//Aggregate query to sum total amount from statement
for(AggregateResult ar: [select sum(Total_Amount__c)totalInvoice,Rental_Agreement__c from Statement__c where Rental_Agreement__c IN:rentalAgreementSet group by Rental_Agreement__c ])    
{
Rental_Agreement__c r = new Rental_Agreement__c(id=string.valueOf(ar.get('Rental_Agreement__c')));
r.Total_Invoiced__c = double.valueOf(ar.get('totalInvoice'));
rentalUpdates.add(r);    
}
if(!rentalUpdates.isEmpty()) 
{
update rentalUpdates;    
}    
}
public static void rollupPaymentsToRentalAgreement(Map<id,Payment__c> newMap)
{
set<id> rentalAgreementSet = new set<id>();
for(Payment__c P: [select id,Statement__r.Rental_Agreement__c from Payment__c where id IN:newMap.keySet()])
{
rentalAgreementSet.add(P.Statement__r.Rental_Agreement__c);    
}    
List<Rental_Agreement__c> rentalUpdates = new List<Rental_Agreement__c>();
for(AggregateResult ar: [select sum(Amount__c)totalPaid, Statement__r.Rental_Agreement__c ra from Payment__c where Statement__r.Rental_Agreement__c IN:rentalAgreementSet group by Statement__r.Rental_Agreement__c])
{
Rental_Agreement__c r = new Rental_Agreement__c(id=string.valueOf(ar.get('ra'))); 
r.Total_Payments__c = double.valueOf(ar.get('totalPaid'));
rentalUpdates.add(r);   
}     
}    
}